name: publish-to-ansible-galaxy
on:
  push:
    branches:
      - main
jobs:
  ansible-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ansible/ansible-publish-action@v1.0.0
      with:
        api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
        api_server: https://beta-galaxy.ansible.com/
        src_path: /github/workspace/dominion_solutions/netbird
