name: publish-to-ansible-galaxy
on:
  release:
    types: [published]
jobs:
  ansible-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ansible/ansible-publish-action@v1.0.0
      with:
        api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
        api_server: https://galaxy.ansible.com/api/
        src_path: /github/workspace/dominion_solutions/netbird
